name: Publish to GitHub Package Registry

on:
  pull_request:
    branches:
      - 'main' # Change this to the branch you want to trigger the deployment from

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Change this to the Node.js version you want to use
        registry-url: https://npm.pkg.github.com/taraldefi

    - name: Install dependencies
      run: npm install

    - name: Bump package version
      id: package-version
      uses: phips28/gh-action-bump-version@v9.1.0
      with:
        tag-prefix: "v"
        skip-verify: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Build package
      run: npm run build # Change this to your build script if needed

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
