name: Publish to GitHub Package Registry

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the deployment from

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Change this to the Node.js version you want to use
        registry-url: https://npm.pkg.github.com/

    - name: Install dependencies
      run: npm ci

    - name: Bump package version
      id: package-version
      uses: phips28/gh-action-bump-version@v10.0.0
      with:
        tag-prefix: "v"
        skip-verify: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build package
      run: npm run build # Change this to your build script if needed

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
