name: Push Trigger

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the deployment from

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deployment workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Publish to GitHub Package Registry
        token: ${{ secrets.GITHUB_TOKEN }}
